/**
 * Interactive HELIX REPL (`helix chat`).
 *
 * Thin loop only (SRP): reads lines, splits slash-commands from tasks,
 * and delegates to `IOrchestratorAgent.dispatch()` — the same entrypoint
 * the one-shot CLI uses, so routing, RAG context, and timeouts behave
 * identically. Errors are printed and the loop continues; only `/exit`
 * (Ctrl+C / Ctrl+D) ends the session.
 *
 * When `OPENROUTER_API_KEY` is set, chat responses are generated by the
 * configured OpenRouter model and augmented with retrieved codebase context
 * and agent reports (when intent flags like `--analyze` are used).
 *
 * Line syntax:
 * - `audit auth for XSS --secure` — task with inline intent flags
 *   (`--analyze/-a`, `--secure/-s`, `--monitor/-m`).
 * - `/agents`, `/index [path]`, `/json`, `/help`, `/exit`.
 */
import { randomUUID } from 'node:crypto';
import { stdin as input, stdout as output } from 'node:process';
import { createInterface } from 'node:readline/promises';
import type winston from 'winston';
import type { AgentIntent, AgentPayload, AgentReport, CliOptions } from '../types/index.js';
import { intentsFromOptions } from './options.js';
import { DEFAULT_TIMEOUT_MS } from './options.js';
import { renderResponse } from './render.js';
import type { CliContext } from './program.js';
import { OpenRouterClient, type ChatMessage } from '../core/llm/OpenRouterClient.js';
import { formatAgentReport } from '../core/llm/formatReport.js';

export interface ChatOptions {
  initialPrompt?: string | undefined;
  json?: boolean | undefined;
  timeoutMs?: number | undefined;
}

interface ChatState {
  json: boolean;
  timeoutMs: number;
  messages: ChatMessage[];
  llmClient?: OpenRouterClient | undefined;
}

export type ChatAction =
  | { kind: 'empty' }
  | { kind: 'task'; prompt: string; intents: AgentIntent[] }
  | { kind: 'command'; name: string; arg: string };

const INTENT_FLAGS: Record<string, AgentIntent> = {
  '--analyze': 'analyze',
  '-a': 'analyze',
  '--secure': 'secure',
  '-s': 'secure',
  '--monitor': 'monitor',
  '-m': 'monitor',
};

const MAX_HISTORY_MESSAGES = 20;
const MAX_CONTEXT_CHARS = 6000;

/** Split one input line into an empty/task/command action. Shared with the TUI. */
export function parseLine(line: string): ChatAction {
  const trimmed = line.trim();
  if (trimmed.length === 0) return { kind: 'empty' };
  if (trimmed.startsWith('/')) {
    const space = trimmed.indexOf(' ');
    if (space === -1) return { kind: 'command', name: trimmed.slice(1).toLowerCase(), arg: '' };
    return { kind: 'command', name: trimmed.slice(1, space).toLowerCase(), arg: trimmed.slice(space + 1).trim() };
  }
  const intents: AgentIntent[] = [];
  const words = trimmed.split(/\s+/).filter((w) => {
    const intent = INTENT_FLAGS[w];
    if (intent === undefined) return true;
    if (!intents.includes(intent)) intents.push(intent);
    return false;
  });
  const prompt = words.join(' ').trim();
  if (prompt.length === 0) return { kind: 'empty' };
  return { kind: 'task', prompt, intents };
}

function printHelp(llmEnabled: boolean): void {
  console.log('Chat commands:');
  console.log('  <task> [--analyze|--secure|--monitor]  send a task (flags run agents + feed the LLM)');
  if (llmEnabled) {
    console.log('  (no flags)                              ask a general coding question with RAG context');
  }
  console.log('  /agents                                 list registered sub-agents');
  console.log('  /index [path]                           (re)index project files for RAG');
  console.log('  /json                                   toggle JSON output');
  console.log('  /help                                   show this help');
  console.log('  /exit                                   quit (Ctrl+C / Ctrl+D also quit)');
}

/** Execute one slash-command. Returns 'exit' when the session should end. */
async function runCommand(ctx: CliContext, name: string, arg: string, state: ChatState): Promise<'exit' | 'continue'> {
  const llmEnabled = state.llmClient !== undefined;
  switch (name) {
    case 'help':
      printHelp(llmEnabled);
      return 'continue';
    case 'exit':
    case 'quit':
      return 'exit';
    case 'agents':
      for (const line of ctx.orchestrator.listAgents()) console.log(`- ${line}`);
      return 'continue';
    case 'json':
      state.json = !state.json;
      console.log(`JSON output ${state.json ? 'on' : 'off'}.`);
      return 'continue';
    case 'index': {
      if (ctx.indexer === undefined) {
        console.log('RAG indexer is not wired in this session.');
        return 'continue';
      }
      console.log(`Indexing ${arg.length > 0 ? arg : 'project root'}…`);
      try {
        const stats = arg.length > 0 ? await ctx.indexer.indexProject(arg) : await ctx.indexer.indexProject();
        console.log(
          `Indexed ${stats.filesIndexed}/${stats.filesScanned} files, ${stats.chunksUpserted} chunks → "${stats.collection}"${stats.fallbackMode ? ' (in-memory fallback)' : ''}.`,
        );
      } catch (err: unknown) {
        console.error(`Indexing failed: ${err instanceof Error ? err.message : String(err)}`);
      }
      return 'continue';
    }
    default:
      console.log(`Unknown command "/${name}". Try /help.`);
      return 'continue';
  }
}

function buildSystemPrompt(): ChatMessage {
  return {
    role: 'system',
    content:
      'You are HELIX, an AI-powered multi-agent software development assistant. ' +
      'You help users review code, audit security, and monitor their local development environment. ' +
      'HELIX automatically runs specialized agents (CodeAgent, SecurityAgent, EnvironmentAgent) when a question ' +
      'calls for code analysis, security scanning, or environment monitoring. ' +
      'When agent reports are provided, answer the user directly using those findings — do not tell them to run a command. ' +
      'When codebase context is provided, ground your answer in that context. ' +
      'Be concise, accurate, and actionable.',
  };
}

async function retrieveContextText(ctx: CliContext, query: string): Promise<string> {
  if (ctx.indexer === undefined) return '';
  // Avoid repeated ChromaDB-unreachable warnings in chat; fallback mode was
  // already logged once during the first retrieval attempt.
  if (ctx.indexer.fallbackMode) return '';
  try {
    const chunks = await ctx.indexer.retrieveContext(query, 5);
    const text = ctx.indexer.formatContext(chunks, MAX_CONTEXT_CHARS);
    return text;
  } catch (err: unknown) {
    ctx.logger.warn('RAG retrieval failed in chat', { error: err instanceof Error ? err.message : String(err) });
    return '';
  }
}

async function dispatchAgents(ctx: CliContext, prompt: string, intents: AgentIntent[], state: ChatState): Promise<AgentReport[]> {
  const traceId = randomUUID();
  const log: winston.Logger = typeof ctx.logger.child === 'function' ? ctx.logger.child({ traceId }) : ctx.logger;
  const options: CliOptions = {
    analyze: intents.includes('analyze'),
    secure: intents.includes('secure'),
    monitor: intents.includes('monitor'),
    verbose: false,
    json: state.json,
    dryRun: false,
    timeoutMs: state.timeoutMs,
  };
  const payload: AgentPayload = { prompt, intents: intentsFromOptions(options), traceId, options };
  log.info('Received chat task', { prompt });
  const reports: AgentReport[] = [];
  try {
    const response = await ctx.orchestrator.dispatch(payload);
    for (const result of response.results) {
      if (typeof result.data === 'object' && result.data !== null && 'issues' in result.data) {
        reports.push(result.data as AgentReport);
      }
    }
    if (response.results.some((r) => !r.success)) {
      ctx.logger.warn('One or more agents reported failure', { traceId });
    }
  } catch (err: unknown) {
    console.error(`Error: ${err instanceof Error ? err.message : String(err)}`);
  }
  return reports;
}

async function runAgentTask(ctx: CliContext, prompt: string, intents: AgentIntent[], state: ChatState): Promise<void> {
  const reports = await dispatchAgents(ctx, prompt, intents, state);
  // In agent-only mode we still render using the existing renderer.
  // (When the LLM is present, it summarizes reports instead.)
  if (reports.length === 0) {
    console.log('No agent results to display.');
  }
}

async function resolveIntents(ctx: CliContext, prompt: string, explicitIntents: AgentIntent[], state: ChatState): Promise<AgentIntent[]> {
  if (explicitIntents.length > 0) return explicitIntents;

  const routePayload: AgentPayload = {
    prompt,
    intents: [],
    traceId: randomUUID(),
    options: {
      analyze: false,
      secure: false,
      monitor: false,
      verbose: false,
      json: false,
      dryRun: false,
      timeoutMs: state.timeoutMs,
    },
  };
  try {
    const decision = await ctx.orchestrator.route(routePayload);
    return decision.intents;
  } catch (err: unknown) {
    ctx.logger.warn('Routing failed in chat; defaulting to analyze', { error: err instanceof Error ? err.message : String(err) });
    return ['analyze'];
  }
}

async function runLlmTask(ctx: CliContext, prompt: string, intents: AgentIntent[], state: ChatState): Promise<void> {
  const llm = state.llmClient;
  if (llm === undefined) return;

  // Auto-route when the user did not provide explicit intent flags.
  const effectiveIntents = await resolveIntents(ctx, prompt, intents, state);
  const reports = effectiveIntents.length > 0 ? await dispatchAgents(ctx, prompt, effectiveIntents, state) : [];

  const contextText = await retrieveContextText(ctx, prompt);

  const parts: string[] = [];
  parts.push(`User request: ${prompt}`);
  if (contextText.length > 0) {
    parts.push('\n--- Codebase context ---\n', contextText);
  }
  if (reports.length > 0) {
    parts.push('\n--- Agent reports ---\n', reports.map(formatAgentReport).join('\n\n'));
  }
  const userContent = parts.join('\n');

  const messages: ChatMessage[] = [buildSystemPrompt(), ...state.messages, { role: 'user', content: userContent }];
  const result = await llm.complete(messages);

  if (!result.ok) {
    console.error(`LLM error: ${result.message}`);
    return;
  }

  console.log(`\n${result.message}\n`);
  if (result.usage !== undefined) {
    ctx.logger.debug('OpenRouter usage', { usage: result.usage, model: result.model });
  }

  // Update conversation history.
  state.messages.push({ role: 'user', content: userContent });
  state.messages.push({ role: 'assistant', content: result.message });
  if (state.messages.length > MAX_HISTORY_MESSAGES) {
    state.messages = state.messages.slice(-MAX_HISTORY_MESSAGES);
  }
}

/** Dispatch one task line: use LLM when available, otherwise pure agents. */
async function runTask(ctx: CliContext, prompt: string, intents: AgentIntent[], state: ChatState): Promise<void> {
  if (state.llmClient !== undefined) {
    await runLlmTask(ctx, prompt, intents, state);
  } else {
    const effectiveIntents = await resolveIntents(ctx, prompt, intents, state);
    if (effectiveIntents.length > 0) {
      await runAgentTask(ctx, prompt, effectiveIntents, state);
    }
  }
}

/**
 * Run the interactive loop. Resolves when the user quits; never rejects
 * on task-level failures (they are printed inline instead).
 *
 * Chat quiets the shared logger to warnings so per-request info traces
 * don't interleave with the prompt — unless `LOG_LEVEL` is set explicitly,
 * in which case the user's choice wins.
 */
export async function runChatLoop(ctx: CliContext, opts: ChatOptions = {}): Promise<void> {
  if (process.env['LOG_LEVEL'] === undefined) {
    ctx.logger.level = 'warn';
  }

  let llmClient: OpenRouterClient | undefined;
  const apiKey = ctx.config.openRouterApiKey;
  if (apiKey !== undefined && apiKey.length > 0) {
    try {
      llmClient = new OpenRouterClient({
        apiKey,
        baseURL: ctx.config.openRouterBaseUrl,
        model: ctx.config.openRouterModel,
        timeoutMs: 120_000,
      });
    } catch (err: unknown) {
      ctx.logger.warn('OpenRouter client could not be initialized; chat will run agent-only.', {
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  const state: ChatState = {
    json: opts.json ?? false,
    timeoutMs: opts.timeoutMs ?? DEFAULT_TIMEOUT_MS,
    messages: [],
    llmClient,
  };

  const interactive = output.isTTY === true;
  const rl = interactive
    ? createInterface({ input, output, prompt: 'helix> ' })
    : createInterface({ input, output, terminal: false });
  rl.on('SIGINT', () => {
    rl.close();
  });

  const llmEnabled = llmClient !== undefined;
  console.log('HELIX interactive mode. Type a task and press Enter.');
  console.log(`LLM chat: ${llmEnabled ? 'enabled (' + ctx.config.openRouterModel + ')' : 'disabled (set OPENROUTER_API_KEY to enable)'}`);
  console.log('Slash commands: /help /agents /index [path] /json /exit');

  const first = opts.initialPrompt?.trim() ?? '';
  if (first.length > 0) {
    await runTask(ctx, first, [], state);
  }
  if (interactive) rl.prompt();
  try {
    for await (const line of rl) {
      const action = parseLine(line);
      if (action.kind === 'empty') {
        if (interactive) rl.prompt();
        continue;
      }
      if (action.kind === 'command') {
        if ((await runCommand(ctx, action.name, action.arg, state)) === 'exit') break;
      } else {
        await runTask(ctx, action.prompt, action.intents, state);
      }
      if (interactive) rl.prompt();
    }
  } finally {
    rl.close();
  }
  console.log('Goodbye.');
}
